logging:
  level:
    root: info

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    embedded-database-connection: h2

#  autoconfigure.exclude: com.example.mylibrary.autoconfigure.LibAutoConfiguration

#config.enable: bfpp
#config.enable: import
#config.enable: scan
